# Copyright 2021 Yubico AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI build for pull requests into main and develop

# Triggers build on pull requests and pushes to the main and develop branches.
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - greg/build-perf

jobs:
  build:
    # Give this job a friendly name to show in GitHub UI.
    name: Build the .NET YubiKey SDK project

    # Even though we build for multiple platforms, we only need to run
    # on a single host operating system. This is because we utilize cross-
    # build functionality of the dotnet build system.
    runs-on: windows-latest

    # Build both Debug and Release configurations.
    strategy:
      matrix:
        configuration: [Debug, ReleaseWithDocs]

    steps:
      # Checkout the local repository
      - uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: List runtimes
        run: dotnet --list-runtimes

      # Build the project
      - name: Build Yubico.NET.SDK.sln
        run: dotnet build --configuration ${{matrix.configuration}} --nologo --verbosity normal Yubico.NET.SDK.sln

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Nuget Packages ${{matrix.configuration}}
          path: |
            Yubico.DotNetPolyfills/src/bin/${{matrix.configuration}}/*.nupkg
            Yubico.Core/src/bin/${{matrix.configuration}}/*.nupkg
            Yubico.YubiKey/src/bin/${{matrix.configuration}}/*.nupkg

      # Test the project
      - name: Test Yubico.YubiKey
        run: dotnet test --configuration ${{matrix.configuration}} --verbosity normal --no-build --nologo Yubico.YubiKey/tests/unit/Yubico.YubiKey.UnitTests.csproj

      - name: Test Yubico.Core
        run: dotnet test --configuration ${{matrix.configuration}} --verbosity normal --no-build --nologo Yubico.Core/tests/Yubico.Core.UnitTests.csproj
